#!/usr/bin/env bash

pl_cpu() {
    case $1 in
      get_freq_min)
        echo "$(__pl_cpu_freq_min)"
        ;;
      get_freq_max)
        echo "$(__pl_cpu_freq_max)"
        ;;
      get_govenor)
        echo "$(__pl_cpu_freq_govenor)"
        ;;
      set_govenor)
        __pl_cpu_set_freq_govenor
        echo "$?"
        ;;
      temp)
        echo "$(__pl_cpu_temp)"
        ;;
    esac
}

__pl_cpu_freq_min() {
  return
}

__pl_cpu_freq_max() {
  return
}

__pl_cpu_freq_govenor() {
  return
}

__pl_cpu_set_freq_govenor() {
  return
}
