#!/usr/bin/env bash

pl-model() {

  case $1 in

    "")
      echo $(awk '{print}' /sys/firmware/devicetree/base/model)
      return 0
      ;;

    is1)
      if [[ $(__pl-model_generation $(__pl-model_rev_code)) -eq 1 ]]; then
        return 0
      else
        return 1
      fi
      ;;

    is2)
      if [[ $(__pl-model_generation $(__pl-model_rev_code)) -eq 2 ]]; then
        return 0
      else
        return 1
      fi
      ;;

    is3)
      rev=$(__pl-model_rev_code)
      gen=$(__pl-model_generation $(rev)) 
      if [[ $(gen)=3 ]]; then
        return 0
      else
        return 1
      fi
      ;;

    is4)
      if [[ $(__pl-model_generation $(__pl-model_rev_code)) -eq 4 ]]; then
        return 0
      else
        return 1
      fi
      ;;

    isZero)
      # Return bool if model=PiZero
      return 0
      ;;

    isCompute)
      # Return bool if model=PiCompute
      return 0
      ;;

  esac
}


__pl-model_rev_code() {
  echo $(awk '/Revision/ {print $3}' /proc/cpuinfo)
}

__pl-model_generation() {
  echo $(awk -v rev_code="$1" '$1==rev_code {print $2}' ./pi_model_data.txt)
}

__pl-model_model() {
  echo $(awk '{print $5}' /sys/firmware/devicetree/base/model)
}

__pl-model_revision() {
  echo $(awk '{print $7}' /sys/firmware/devicetree/base/model)
}