#!/usr/bin/env bash

pl_cpu() {
    case $1 in
      freq_current)
        echo "$(__pl_cpu_freq_cur)"
        ;;
      freq_min)
        echo "$(__pl_cpu_freq_min)"
        ;;
      freq_max)
        echo "$(__pl_cpu_freq_max)"
        ;;
      govenor)
        echo "$(__pl_cpu_govenor $@)"
        ;;
      govenor_up_threshold)
        echo "$(__pl_cpu_gov_up_threshold $@)"
        ;;
      govenor_down_threshold)
        echo "$(__pl_cpu_gov_down_threshold $@)"
        ;;
      temp)
        echo "$(__pl_cpu_temp)"
        ;;
    esac
}

__pl_cpu_freq_min() {
  return
}

__pl_cpu_freq_max() {
  return
}

__pl_cpu_freq_govenor() {
  return
}

__pl_cpu_set_freq_govenor() {
  return
}

__pl_cpu_temp() {
  temp=$(cat /sys/class/thermal/thermal_zone0/temp)/1000
  echo "$temp"
}