#!/usr/bin/env bash


case $1 in
  all)
    ./tests/libs/bats/bin/bats ./tests/*.bats
    ;;
  audio)
    return
    ;;
  bt)
    return
    ;;
  camera)
    return
    ;;
  cpu)
    return
    ;;
  csi)
    return
    ;;
  gpio)
    return
    ;;
  gpu)
    ./tests/libs/bats/bin/bats ./tests/pishlib-gpu.bats
    ;;
  mem)
    ./tests/libs/bats/bin/bats ./tests/pishlib-mem.bats
    ;;
  model)
    ./tests/libs/bats/bin/bats ./tests/pishlib_model.bats
    ;;
  screen)
    ;;
  wifi)
    ;;
esac
